#! /usr/bin/env python
import os
import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('old', type=str, help='the old ext')
    parser.add_argument('new', type=str, help='the new ext')
    parser.add_argument('--path', type=str, help='work directory')
    parser.add_argument('-v', '--verbose', action='store_true', help='show details')
    args = parser.parse_args()
    old, new = args.old, args.new
    path = args.path if args.path else '.'
    if args.verbose:
        print(f"[--] work directory is {os.path.realpath(path)}")
    try:
        for file in os.listdir(path):
            file = os.path.join(path, file)
            if os.path.isfile(file):
                pre, ext = os.path.splitext(file)
                if ext.strip('.') == old:
                    if args.verbose:
                        print(f"[##] rename {file} to {pre}.{new}")
                    os.rename(file, f"{pre}.{new}")
                else:
                    if args.verbose:
                        print(f'[!!] skip file {file}')
            else:
                if args.verbose:
                    print(f'[!!] skip directory {file}')
    except Exception as e:
        print(e)
