#! /usr/bin/env python3
import argparse
import os.path

from PIL import Image

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='icon generator')

    parser.add_argument("file", help="input image path", type=str)

    parser.add_argument("-o", "--out", help="output dir", type=str, default="icons")

    parser.add_argument("-f", "--format", help="output format", type=str, default="png")

    parser.add_argument("--sizes", help="output sizes", nargs="+", default=[16, 32, 48, 64, 128, 256, 512])

    parser.add_argument('-v', '--verbose', action='store_true')

    args = parser.parse_args()

    if not os.path.exists(args.file):
        raise Exception("Input file does not exists.")

    if not os.path.exists(args.out):
        os.makedirs(args.out)

    with Image.open(args.file) as img:
        if args.verbose:
            print(f'{img.format}, {img.size}, {img.mode}')
        for size in args.sizes:
            output = os.path.join(args.out, f'{size}x{size}.{args.format}')
            out = img.resize((size, size))
            out.save(output)
            if args.verbose:
                print(f"{output} done!")
