[tool.poetry]
name = "pythonutils"
version = "0.1.0"
description = ""
authors = ["Archean-w <1091876908@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pillow = "^10.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
